# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\x12\x06search\"8\n\x08TermInfo\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x0e\n\x06length\x18\x03 \x01(\x05\"<\n\x08\x44ocument\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x1f\n\x05terms\x18\x02 \x03(\x0b\x32\x10.search.TermInfo\")\n\x0bPostingItem\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\n\n\x02tf\x18\x02 \x01(\x02\"1\n\x0bPostingList\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.search.PostingItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERMINFO']._serialized_start=26
  _globals['_TERMINFO']._serialized_end=82
  _globals['_DOCUMENT']._serialized_start=84
  _globals['_DOCUMENT']._serialized_end=144
  _globals['_POSTINGITEM']._serialized_start=146
  _globals['_POSTINGITEM']._serialized_end=187
  _globals['_POSTINGLIST']._serialized_start=189
  _globals['_POSTINGLIST']._serialized_end=238
# @@protoc_insertion_point(module_scope)
